"""BusinessPlan Refactor

Revision ID: 61c5384125d2
Revises: dd55d3a36c6e
Create Date: 2026-02-22 08:05:40.133700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c5384125d2'
down_revision: Union[str, None] = 'dd55d3a36c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_section_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_plan_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('suggestions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['business_plan_id'], ['business_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_section_analyses_id'), 'plan_section_analyses', ['id'], unique=False)
    op.add_column('business_plans', sa.Column('content_markdown', sa.Text(), nullable=True))
    op.add_column('business_plans', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('business_plans', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.drop_column('business_plans', 'content_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_plans', sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('business_plans', 'overall_score')
    op.drop_column('business_plans', 'executive_summary')
    op.drop_column('business_plans', 'content_markdown')
    op.drop_index(op.f('ix_plan_section_analyses_id'), table_name='plan_section_analyses')
    op.drop_table('plan_section_analyses')
    # ### end Alembic commands ###
