"""Add missing tables

Revision ID: a2027d7c3dc5
Revises: b4b7753d4fa9
Create Date: 2026-02-18 20:20:58.656168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2027d7c3dc5'
down_revision: Union[str, None] = 'b4b7753d4fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consulting_requests', sa.Column('meeting_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consulting_requests', 'meeting_link')
    # ### end Alembic commands ###
