"""Add access_level to user

Revision ID: aac2c8d01c86
Revises: 61c5384125d2
Create Date: 2026-02-22 10:34:09.896678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac2c8d01c86'
down_revision: Union[str, None] = '61c5384125d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_level')
    # ### end Alembic commands ###
