"""Update project fields

Revision ID: dd55d3a36c6e
Revises: a2027d7c3dc5
Create Date: 2026-02-20 10:49:04.207777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd55d3a36c6e'
down_revision: Union[str, None] = 'a2027d7c3dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('main_sector', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('business_model', sa.String(), nullable=True))
    op.drop_column('projects', 'business_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'business_model')
    op.drop_column('projects', 'main_sector')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
